### ISSUE TITLE
Not start the node when public IP is not known

### ISSUE THREAD

**Issue by bakhshandeh** [muon-protocol/muon-node-js#260]
Currently, the node runs and logs `MuonRouting multiaddrs is empty` when it can't find the public IP.

**Comment by sadeghte** [comment]
Occasionally, the `ifconfig` service returns a response like this:

```javascript
{
      success: true,
      ip_addr: "209.250.252.247, 172.70.46.211"
}
```

**Comment by fofaraz** [comment]
> Occasionally, the `ifconfig` service returns a response like this:
> 
> ```js
> {
>       success: true,
>       ip_addr: "209.250.252.247, 172.70.46.211"
> }
> ```

this bug is resolved in this commit
https://github.com/muon-protocol/muon-node-js/pull/279

**Comment by bakhshandeh** [comment]
@sadeghte should we add this code again?
https://github.com/muon-protocol/muon-node-js/commit/775f89b1363b3eb25efd3985d78d7bbaf61e9e11

**Comment by sadeghte** [comment]
The ipv6 problem still exists. We should find a solution for it before we add those codes.

**Comment by bakhshandeh** [comment]
@sadeghte  the issue with ifconfig is fixed now. Can we enable not starting the node when the IP is unknown again?
